### ISSUE TITLE
how use with kubernetes dashboard

### ISSUE THREAD

**Issue by ilanni2460** [tiagoapimenta/nginx-ldap-auth#8]
how use with kubernetes dashboard

**Comment by tiagoapimenta** [comment]
if you read [README.md](https://github.com/tiagoapimenta/nginx-ldap-auth/blob/master/README.md) file you will see the configuration is made on ingress, same way as documented on [nginx](https://kubernetes.github.io/ingress-nginx/examples/auth/external-auth/), to use it on dashboard you need to access Ingress view, and change the configuration.

-----------
About [your comment here](https://github.com/kubernetes/ingress-nginx/issues/1676#issuecomment-451343543), I do not know this product, but if it provides LDAP integration, maybe it just works, if it does not, it requires a complete different solution.

**Comment by m0se** [comment]
@ilanni2460 If you are still looking for a way to use nginx-ldap-auth with kubernetes-dashboard, I have a quick&dirty hack for you...

**It is definitively not the proper way to do it and this is no solution for a production cluster with different access levels for different users**

I just needed a simple way to grant LDAP users full access to the dashboard.

You can basically just use the configuration-snippet annotation in your ingress to set the `jwetoken` header to a valid auth token for the dashboard. 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
   nginx.ingress.kubernetes.io/auth-url: http://<nginx-ldap-auth>:5555
   nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header jwetoken '{"protected":"...
```
This way you authenticate to the ingress with LDAP and the ingress authenticates with the hard-coded token against the actual dashboard. You probably need to make sure that the token never expires and that the format you put in configuration-snippet is correct, but it works for me.
